"""simplified pronunciation

Revision ID: 178253888b
Revises: 1c1883fada8
Create Date: 2015-08-07 23:08:13.240049

"""

# revision identifiers, used by Alembic.
revision = '178253888b'
down_revision = '1c1883fada8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('simplified_pronunciation', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('word', 'simplified_pronunciation')
    # it is not supported by sqlite
    with op.batch_alter_table("word") as batch_op:
        batch_op.drop_column('simplified_pronunciation')
