"""Init

Revision ID: 33886df91c1
Revises:
Create Date: 2015-08-09 01:14:34.445962

"""

# revision identifiers, used by Alembic.
revision = '33886df91c1'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('name', sa.UnicodeText(), nullable=False),
        sa.Column('foreign_language', sa.Enum('en', 'pl', 'fr', 'es'), nullable=False),
        sa.Column('known_language', sa.Enum('en', 'pl', 'fr', 'es'), nullable=True),
        sa.Column('definitions', sa.Boolean(), server_default=sa.false(), nullable=True),
        sa.Column('pictorials', sa.Boolean(), server_default=sa.false(), nullable=True),
        sa.Column('last_visited_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_name'), 'list', ['name'], unique=False)

    op.create_table(
        'word',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('language', sa.Enum('en', 'pl', 'fr', 'es'), nullable=False),
        sa.Column('word', sa.UnicodeText(), nullable=False),
        sa.Column('ipa', sa.UnicodeText(), nullable=True),
        sa.Column('simplified', sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('word', 'language', name='_word_language_uc')
    )
    op.create_table(
        'card',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('word_id', sa.Integer(), nullable=False),
        sa.Column('language', sa.Enum('en', 'pl', 'fr', 'es'), nullable=True),
        sa.Column('translation', sa.UnicodeText(), nullable=True),
        sa.Column('picture', sa.UnicodeText(), nullable=True),
        sa.Column('definition', sa.UnicodeText(), nullable=True),
        sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_word_id'), 'card', ['word_id'], unique=False)

    op.create_table(
        'card_assignment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('card_id', sa.Integer(), nullable=False),
        sa.Column('list_id', sa.Integer(), nullable=False),
        sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
        sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('card_id', 'list_id', name='_card_list_uc')
    )
    op.create_index(op.f('ix_card_assignment_card_id'), 'card_assignment', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_assignment_last_accessed_at'), 'card_assignment', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_card_assignment_list_id'), 'card_assignment', ['list_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_assignment_list_id'), table_name='card_assignment')
    op.drop_index(op.f('ix_card_assignment_last_accessed_at'), table_name='card_assignment')
    op.drop_index(op.f('ix_card_assignment_card_id'), table_name='card_assignment')
    op.drop_table('card_assignment')
    op.drop_index(op.f('ix_card_word_id'), table_name='card')
    op.drop_table('card')
    op.drop_table('word')
    op.drop_index(op.f('ix_list_name'), table_name='list')
    op.drop_table('list')
    ### end Alembic commands ###
